---
- name: Create IBM Cloud VPC VSI
  hosts: localhost
  collections:
   - ibm.cloudcollection

  tasks:
    - name: get resource groud id
      ibm_resource_group_info:
        name: "{{ resource_group }}"
      register: resource_group_info

    - name: get ssh key id
      ibm_is_ssh_key_info:
        name: "{{ ssh_public_key }}"
      register: ssh_info

    - name: get vpc id
      ibm_is_vpc_info:
        name: "{{ vpc }}"
      register: vpc_info

    - name: get subnet id
      ibm_is_subnet_info:
        name: "{{ subnet }}"
      register: subnet_info

    - name: Configure VSI
      ibm_is_instance:
        resource_group: "{{ resource_group_info.resource.id }}"
        name: "{{ name_prefix }}-vsi"
        state: available
        vpc: "{{ vpc_info.resource.id }}"
        profile: "{{ vsi_profile }}"
        image: "{{ vsi_image }}"
        keys:
          - "{{ ssh_info.resource.id }}"
        primary_network_interface:
          - subnet: "{{ subnet_info.resource.id }}"
        zone: "{{ zone }}"
        region: "{{ region }}"
      register: vsi

    - debug:
        msg: "{{ vsi.resource.primary_network_interface[0]['id'] }}"

    - name: Configure Floating IP Address
      ibm_is_floating_ip:
        resource_group: "{{ resource_group_info.resource.id }}"
        name: "{{ name_prefix }}-fip"
        state: available
        target: "{{ vsi.resource.primary_network_interface[0]['id'] }}"
      register: fip

    - debug:
        msg: "{{ fip }}"

    - name: Create tower inventory
      tower_inventory:
        name: "IBM Cloud"
        description: "VSIs"
        organization: "Default"
        state: present

    - name: Add tower host
      tower_host:
        name: "{{ name_prefix }}-vsi"
        inventory: "IBM Cloud"
        state: present
        variables:
           ansible_host: "{{ fip.resource.address }}"


