---
- hosts: "{{ vsi_image }}"
  vars:
  - ansible_user: root
  - warName: HelloTommi.war
  - warLocation: /tmp
  - artifactory_url: http://artifactory.sohlberg.io:8081/artifactory/helloTommi
  - tomcatPath: /opt/tomcat

  tasks:
  - name: Install Unzip
    yum:
      name: unzip
      state: present

  - name: Download WAR file to a server
    get_url:
      url: "{{ artifactory_url }}/{{ warName }}"
      dest: "{{ warLocation }}/{{ warName }}"

  - name: Unzip WAR file
    unarchive: src={{ warLocation }}/{{ warName }} dest={{ tomcatPath }}/webapps/ROOT/ copy=no mode=0664 owner=tomcat group=tomcat
    notify:
        -  Restart Tomcat Server

  - name: Delete remote war file
    file: path={{ warLocation }}/{{ warName }} state=absent

  handlers:
    - name: Restart Tomcat Server
      service: name=tomcat state=restarted