---
- name: Delete IBM Cloud VPC VSI
  hosts: localhost

  tasks:
    - name: get floating ip id
      ibm.cloudcollection.ibm_is_floating_ip_info:
        name: "{{ name_prefix }}-fip"
      register: floating_ip

    - name: release floating ip
      ibm.cloudcollection.ibm_is_floating_ip:
        id: "{{ floating_ip.resource.id }}"
        state: absent

    - name: get vsi id
      ibm.cloudcollection.ibm_is_instance_info:
         name: "{{ name_prefix }}-vsi"
      register: instance

    - name: destroy a vm
      ibm.cloudcollection.ibm_is_instance:
         id: "{{ instance.resource.id }}"
         state: absent
         keys: []

    - name: Add tower host
      awx.awx.tower_host:
        name: "{{ name_prefix }}-vsi"
        inventory: "IBM Cloud"
        state: absent
        validate_certs: no