- hosts: all
  vars:
    ansible_user: root
    tomcat_version: 8.5.63

  pre_tasks:
  - name: Sleep for 30 seconds and continue with play
    pause:
      seconds: 30

  - name: Install tar
    yum:
      name: tar
      state: present
  roles:
    - zaxos.tomcat-ansible-role