- hosts: "{{ vsi_image }}"
  vars:
    ansible_user: root
    tomcat_version: 8.5.63

  pre_tasks:
  - name: Sleep for 90 seconds and continue with play
    pause:
      seconds: 90
    when: vsi_image == 'RHEL7'

  - name: Install tar
    yum:
      name: tar
      state: present

  roles:
    - zaxos.tomcat-ansible-role