- hosts: localhost

  tasks:
  - debug:
      var: "{{ inventory_hostname }}"
  - msg: "{{ inventory_hostname }}"

  - name: Check that a page returns a status 200 and fail if the word Tommi is not in the page contents
    uri:
      url: "http://{{ ansible_hostname }}:8080"
      return_content: yes
    with_inventory_hostnames:
      - all
    register: this
    failed_when: "'Tommi' not in this.content"
