- hosts: localhost

  tasks:
  - name: Check that a page returns a status 200 and fail if the word Tommi is not in the page contents
    uri:
      url: "http://{{ item }}:8080"
      return_content: yes
    with_inventory_hostnames:
      - all
    register: this
    failed_when: "'Tommi' not in this.content"
