- hosts: all

  tasks:
  - name: Check that a page returns a status 200 and fail if the word Tommi is not in the page contents
    uri:
      url: http://{{ ansible_host }}:8080
      return_content: yes
    register: this
    failed_when: "'Tommi' not in this.content"
