- hosts: all

  tasks:
  - name: Check my custom web page returns HTTP 200 and check content
    ansible.builtin.uri:
      url: "http://{{ hostvars[inventory_hostname].ansible_host }}:8080"
      return_content: yes
    with_inventory_hostnames:
      - all
    register: this
    failed_when: "'Tommi' not in this.content"
    delegate_to: localhost
