- hosts: all

  tasks:
  - name:  Login to the Tomcat Management Console
    ansible.builtin.uri:
      url: "http://{{ hostvars[inventory_hostname].ansible_host }}:8080/manager/html"
      method: GET
      url_username: "{{ tomcat_username }}"
      url_password: "{{ tomcat_password }}"
      status_code: 200
      return_content: yes
    register: this
    failed_when: "'Tomcat Web Application Manager' not in this.content"
    delegate_to: localhost